MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.33"
SiteTitle: Pandora Pocket
SiteDescription: IT系と日常系の備忘録。三日坊主。
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{title} - {siteTitle}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: entry/**/*
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml
GenerateSearchIndex: true